### ISSUE TITLE
I am able to login and split bills. But "Wireless Total" is always 0.00 for any particular month

### ISSUE THREAD

**Issue by ArtixZ** [brianzq/att-bill-splitter#13]

**Comment by brianzq** [comment]
Those cases are always annoying. I suspect the bill page returned doesn't have the info we need. There could be different reasons and it's hard to debug without inspecting the page that actually got returned. If you are comfortable with python, you can modify the code and write the returned bill page to local and check what's in there. More specifically, add this line after line 
`open('bill.html', 'w').write(bill_html.encode('utf-8'))` after https://github.com/brianzq/att-bill-splitter/blob/master/attbillsplitter/main.py#L263. Or you can join the [slack channel ](https://join.slack.com/t/att-bill-splitter/shared_invite/enQtMjk5Mzc4NTQ4ODY5LWRmMWQzYjM2MWFmYzE1NjY1N2MzOTkyZGJhNDMzNGJjOWFhNzI4OTRkZTg4MmM3YzY0YzMwODMxZTI4NGYzZDI) for more involved discussion.

**Comment by ArtixZ** [comment]
With the latest version. This issue is gone. Thanks a lot for your effort. 
BTW, I'm open to contribute if something's needed.
Thanks!
